Column directive reactivity for input props.
carbon-design-system/carbon-components-angular pull request #2386
Opened 2022-12-15 19:48 UTC by Dagdelo

The current implementation lacks reactivity for the input props. Now, when a prop changes the directive will reflect these changes. This feature is required when the application needs to dynamically change the columns' disposition.

Closes carbon-design-system/carbon-components-angular#2385

2022-12-15 19:50 UTC, Dagdelo commented
recheck

2022-12-15 19:51 UTC, Dagdelo commented
recheck

2023-01-05 20:52 UTC, Akshat55 commented
@Dagdelo Going to review this sometime next week. There was some changes made in next branch that we can use here. We _**might**_ be able to use observable here.

2023-01-17 04:25 UTC, Akshat55 requested changes

2023-01-17 04:25 UTC, Akshat55 commented on src/grid/grid.directive.ts
> +import { Directive, HostBinding, Input, OnInit, OnChanges, SimpleChanges } from "@angular/core";
```suggestion
import { 
	Directive,
	HostBinding,
	Input,
	OnChanges,
	SimpleChanges
} from "@angular/core";
```

2023-01-17 04:25 UTC, Akshat55 commented on src/grid/grid.directive.ts
> +export class ColumnDirective implements OnInit, OnChanges {
```suggestion
export class ColumnDirective implements OnChanges {
```

2023-01-17 04:25 UTC, Akshat55 commented on src/grid/grid.directive.ts
> +  	}
```suggestion
```

2023-01-17 04:25 UTC, Akshat55 commented on src/grid/grid.directive.ts
> +export class ColumnDirective implements OnInit, OnChanges {
We can just remove OnInit and add the logic inside OnChanges

2023-01-17 15:47 UTC, Akshat55 requested changes

2023-01-17 15:47 UTC, Akshat55 commented on src/grid/grid.directive.ts
> +	SimpleChanges
```suggestion
	OnChanges
```

2023-01-17 15:47 UTC, Akshat55 commented on src/grid/grid.directive.ts
> +			this.columnClasses = "";
```suggestion
			this._columnClasses = "";
```

2023-01-17 16:32 UTC, Akshat55 approved these changes

2023-01-17 16:37 UTC, zvonimirfras approved these changes

2023-01-17 16:37 UTC, merged