feat: Add Edit on Carbon UI builder buttons to storybook
carbon-design-system/carbon-components-angular pull request #2416
Opened 2023-01-25 21:20 UTC by MoizMasud

Signed-off-by: Moiz Masud <moizkhan_007@hotmail.com>
Closes [carbon-design-system/carbon-components-angular#](https://github.com/carbon-design-system/carbon-components-angular/issues/2415)

2023-01-27 20:17 UTC, Akshat55 requested changes
Should remove the link to the stories that aren't possible in UI builder. Examples of this would be toolbar search, expandable toolbar search, skeletons, etc.

For the time being it's best to add links to the `basic` stories. We can circle back in the future and the story links for the more complicated stories.

2023-01-30 15:43 UTC, Akshat55 requested changes
Hey, can we also readd the links to the `Clickable`, `Selectable`, `Multi-select` & `Expandable` tiles? We have those as a component so we can add the link.

2023-01-30 18:51 UTC, Akshat55 approved these changes

2023-01-30 20:04 UTC, zvonimirfras approved these changes

2023-01-30 20:04 UTC, merged