fix: dropdown list keyboard scroll not working
carbon-design-system/carbon-components-angular pull request #2471
Opened 2023-03-02 13:04 UTC by rhythm55

Closes: [#2389](https://github.com/carbon-design-system/carbon-components-angular/issues/2389)

Dropdown list was scrollable using mouse but with keyboard list was not scrolling. checked keyboard navigation of dropdown list `navigateList` and found out that upon navigation from arrow keys html elements were missing with scroll behavior. On adding `scrollIntoView` the list scroll is working as expected with keyboard.
Took dropdown list scroll behavior reference from - [carbon design react](https://react.carbondesignsystem.com/?path=/story/components-dropdown--default)

**Before**
![issue](https://user-images.githubusercontent.com/36883992/222426907-a3166f41-14b0-447d-a521-477a83923762.gif)

**After**
![issue](https://user-images.githubusercontent.com/36883992/222426556-22faab74-31ff-46cf-ad77-78efaa502e99.gif)

2023-03-02 13:06 UTC, rhythm55 commented
I have read the DCO document and I hereby sign the DCO.

2023-03-02 13:15 UTC, Akshat55 commented
Hey @rhythm55, could you please add additional list items to the story? This will make it easier to test out.

2023-03-03 16:51 UTC, Akshat55 requested changes
Removing smooth scrolling behavior to match the React behavior. There _could_ also be accessibility concerns with smooth scrolling behavior, hence best to remove in this case.

2023-03-03 16:51 UTC, Akshat55 commented on src/dropdown/list/dropdown-list.component.ts
> +					this.getNextElement().scrollIntoView({behavior: "smooth", block: "end"});
```suggestion
					this.getNextElement().scrollIntoView({ block: "end" });
```

2023-03-03 16:51 UTC, Akshat55 commented on src/dropdown/list/dropdown-list.component.ts
> +					this.getPrevElement().scrollIntoView({behavior: "smooth"});
```suggestion
					this.getPrevElement().scrollIntoView();
```

2023-03-03 19:33 UTC, zvonimirfras approved these changes

2023-03-03 19:34 UTC, merged