fix: add helper invalid and warning text in radio group
carbon-design-system/carbon-components-angular pull request #2501
Opened 2023-03-28 18:49 UTC by rhythm55

Closes carbon-design-system/carbon-components-angular#

{{short description}}

#### Changelog

**New**

* {{new thing}}

**Changed**

* {{change thing}}

**Removed**

* {{removed thing}}

2023-04-06 00:04 UTC, Akshat55 requested changes
Let's make the requested changes for the time being and we can come back to the `display:none` issue next week.

2023-04-06 00:04 UTC, Akshat55 commented on src/radio/radio-group.component.ts
> +		</div>
Can we update the template to match React where we wrap the radio buttons in a fieldset? That's a more appropriate way to group the radio buttons.

2023-06-16 19:33 UTC, Akshat55 approved these changes

2023-06-16 19:36 UTC, zvonimirfras approved these changes

2023-06-16 20:15 UTC, merged