fix(date-picker) Specify type for flatpickrOptions
carbon-design-system/carbon-components-angular pull request #2666
Opened 2023-07-28 10:25 UTC by flisijn

Closes carbon-design-system/carbon-components-angular#2665

Add the type for the flatpickrOptions input in the Date picker component

2023-07-28 10:42 UTC, flisijn commented
I have read the DCO document and I hereby sign the DCO.

2023-07-28 10:42 UTC, flisijn commented
recheck

2023-08-19 21:03 UTC, Akshat55 requested changes

2023-08-19 21:03 UTC, Akshat55 commented on src/datepicker/datepicker.component.ts
> +	protected _flatpickrOptions : flatpickr.Options.Options = {
```suggestion
	protected _flatpickrOptions : Options = {
```

Additionally with this change, you should be able to remove the `@ts-ignore` comments that suppressed the type errors previously!

2023-08-19 21:03 UTC, Akshat55 commented on src/datepicker/datepicker.component.ts
> +	get flatpickrOptions(): flatpickr.Options.Options {
You may also need to type cast the Object that is returned. You can do so by appending `as Options;` AFTER the shallow copy (`Object.assign`)

2024-03-28 03:16 UTC, Akshat55 approved these changes

2024-03-28 21:53 UTC, merged