feat: add password input
carbon-design-system/carbon-components-angular pull request #2772
Opened 2024-01-28 16:22 UTC by maicongodinho

Closes carbon-design-system/carbon-components-angular#1930

This update introduces a new password input component along with its corresponding sub-components.

2024-01-28 16:28 UTC, maicongodinho commented
In the context of React components, where a "directive-like" solution is not employed, my approach to the new component involves maintaining the use of projection. A type flag is utilized to seamlessly switch between templates representing different input types, thus ensuring native HTML5 password handling.

To implement this, users are required to utilize two inputs accompanied by the `cdsPassword` directive, each configured with distinct types (text and password). The `cds-password-label` is then responsible for managing these inputs effectively.

Building upon the React component reference found at https://react.carbondesignsystem.com/?path=/story/components-textinput--toggle-password-visibility:

2024-05-14 12:37 UTC, hubertmalkowski commented
Sorry to butt in, butt is there any update on this PR?

2024-05-14 22:36 UTC, Akshat55 commented
Sorry, been preoccupied, let me prioritize this for this week and we can hopefully merge it sometimes next week. @maicongodinho, I'm going to make a few simplifications to this. I want to be able to toggle input property type so users don't have to project both `input[type="text"]` and `input[type="password"]`.

2024-05-14 22:58 UTC, maicongodinho commented
Hey @Akshat55, indeed, this is an older implementation. I aimed to leverage the directive style, integrating best practices in security and accessibility from the React library. While exploring simplification within our existing structure, I couldn't find an optimal solution. However, we could consider developing a new, consolidated component that combines the functionality of labels and password features seamlessly. Let me know what you think and what you need from my side.

2024-05-21 23:39 UTC, maicongodinho commented
Hi @Akshat55, I just saw the approach you took. Excellent use of setting the property to the native element. I hadn't considered this method myself. Really good work!

2024-05-23 15:38 UTC, Akshat55 requested changes

2024-05-23 15:38 UTC, Akshat55 commented on src/input/password-input-label.component.ts
> +		>
```suggestion
			}">
```

2024-05-23 15:38 UTC, Akshat55 commented on src/input/password-input-label.component.ts
> +
```suggestion
```

2024-05-23 19:50 UTC, Akshat55 approved these changes

2024-05-23 20:33 UTC, zvonimirfras commented on src/input/password.spec.ts
> +				type="password">
```suggestion
			<input cdsPassword type="password">
```

2024-05-28 22:07 UTC, zvonimirfras approved these changes

2024-05-29 19:33 UTC, Akshat55 approved these changes

2024-05-29 19:33 UTC, merged