fix: expose experimental autoAlign input on icon button
carbon-design-system/carbon-components-angular pull request #2856
Opened 2024-04-10 11:21 UTC by Geoffrey0

Closes carbon-design-system/carbon-components-angular#2855

The icon button did not yet expose the autoAlign input to enable the experimental floating-ui tooltip functionality. 

#### Changelog

**New**

* Added experimental autoAlign input on icon button component

2024-04-10 14:08 UTC, Akshat55 requested changes
Could you add a separate story for autoAlign? This way users can actually test it. You can reference the popover.stories.ts:

https://github.com/carbon-design-system/carbon-components-angular/blob/27e4e6c14e1aa1b0d3229a78e9f1a6dfbfcf96cf/src/popover/popover.stories.ts#L125

Since `autoalign` is not toggle-able for the time being, it's best to have a story showcasing the auto alignment.

2024-04-10 15:38 UTC, Geoffrey0 commented
Added the separate story indeed. Thanks for the feedback 🙏

2024-04-10 17:06 UTC, Akshat55 requested changes
We want to showcase that scrolling will change the position

2024-04-10 17:06 UTC, Akshat55 commented on src/button/icon-button.stories.ts
> +		</cds-icon-button>
```suggestion
		<div style="height:3000px">
			Scrolling will update the position of the popover:
			<div style="position: absolute; top: 500px; left: 500px;">
				<cds-icon-button
					buttonId="icon-btn1"
					type="button"
					[kind]="kind"
					[size]="size"
					[align]="align"
					[isOpen]="isOpen"
					[autoAlign]="autoAlign"
					[buttonNgClass]="buttonNgClass"
					[buttonAttributes]="buttonAttributes"
					[disabled]="disabled"
					[description]="description"
					(click)="onClick($event)"
					(mouseenter)="onMouseEnter($event)"
					(mouseleave)="onMouseleave($event)"
					(focus)="onFocus($event)"
					(blur)="onBlur($event)">
					<svg class="cds--btn__icon" cdsIcon="copy" size="16"></svg>
				</cds-icon-button>
			</div>
		</div>
```

2024-04-10 17:06 UTC, Akshat55 commented on src/button/icon-button.stories.ts
> +	align: "top"
```suggestion
	align: "top",
	isOpen: true
```

2024-04-10 17:07 UTC, Akshat55 commented
Good to merge after those change

2024-04-11 14:21 UTC, Akshat55 commented on src/button/icon-button.stories.ts
> +					[autoAlign]="autoAlign"
```suggestion
					[autoAlign]="autoAlign"
					[isOpen]="isOpen"
```

2024-04-11 15:24 UTC, Akshat55 approved these changes

2024-04-11 17:59 UTC, zvonimirfras approved these changes

2024-04-11 18:04 UTC, merged