feat: table expand all rows feature
carbon-design-system/carbon-components-angular pull request #3014
Opened 2024-09-27 07:37 UTC by eduardmarcinco

Closes carbon-design-system/carbon-components-angular#2928

This PR adds a capability to expand / collapse all rows in table.
It can be done by clicking on the icon in the table header or by calling a method on `TableModel`.

<img width="867" alt="image" src="https://github.com/user-attachments/assets/320bdeeb-b6b1-45e4-aec1-a51bb7c8267b">

2024-10-01 02:40 UTC, Akshat55 requested changes

2024-10-01 02:40 UTC, Akshat55 commented on src/table/head/table-head-expand.component.ts
> +	@Output() change = new EventEmitter<boolean>();
We can probably just call it `expanded` and `expandedChange` to allow for double binding. This is in case user is creating their own table.

2024-10-01 02:40 UTC, Akshat55 commented on src/table/head/table-head-expand.component.ts
> +		>
```suggestion
			(click)="change.emit(!allRowsExpanded)">
```

2024-10-01 14:38 UTC, Akshat55 submitted a review, later dismissed
Awesome! Thanks for contributing this 🎉

2024-10-15 14:37 UTC, Akshat55 approved these changes

2024-10-15 14:46 UTC, zvonimirfras approved these changes

2024-10-15 14:46 UTC, merged